name: whatchadoin

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  peeking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm install
      - run: npm run readme
      - name: push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: "master"
          commit-message: "Automated README.md update"
          force-add: "true"
          files: README.md
          name: Manuel Muñoz Solera
          email: mamuso@mamuso.net
